version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cost_monitoring_db
    restart: always
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password_99
      POSTGRES_DB: cost_monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
