global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'capstone_backend_telemetry'
    static_configs:
      # Connects directly to our backend microservice container running inside the network bridge
      - targets: ['backend:8000']
